name: Update dependencies
run-name: Update dependencies

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v2

      - name: Get dependencies
        run: .\get-dependencies.ps1

      - name: Update dependencies
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dependencies
          file_pattern: bin/MinSudo.exe
